name: Continuous Integration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_merkletreers_library:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --release

  merkle_root:
    needs: ["build_merkletreers_library"]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Run merkle_root tests
        run: cargo test merkle_root

  merkle_proof:
    needs: ["build_merkletreers_library"]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Run merkle_proof tests
        run: cargo test merkle_proof

  merkle_proof_check:
    needs: ["build_merkletreers_library"]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Run merkle_proof_check tests
        run: cargo test merkle_proof_check
