name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Tests
      run: cargo test